### ISSUE TITLE
[FEAT] 이미지 최적화, CSS 

### ISSUE THREAD

**Issue by Yuiii0** [Yuiii0/meongnyang-life#54]
## Description
> 이미지 최적화 작업과 CSS 스타일링 작업을 수행합니다.

## Todo
- [x] webp 파일변환
- [x] width, height, aspect-ratio 지정
- [ ] srcset, sizes 적용으로 반응형 이미지 제공 
- [x] lazy loading 적용
- [x] Post 파일 첨부 컴포넌트 스타일링
- [x] Post 이미지 스타일링
