### ISSUE TITLE
[FEAT] Auth React-query 적용 

### ISSUE THREAD

**Issue by Yuiii0** [Yuiii0/meongnyang-life#63]
## Description
> auth api에 react-query를 적용하고 파일 이동 작업을 수행합니다.

## Todo
- [x] auth api 수정
- [x] react-query 적용
- [x] firebase shared 파일로 이동
